name: Build papers
on: [push, pull_request]
jobs:
  launch_test:
    name: Build papers
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install prerequisite
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://miktex.org/download/win/miktexsetup-x64.zip" -OutFile "miktexsetup-x64.zip" && Expand-Archive miktexsetup-x64.zip && cd miktexsetup-x64 && ./miktexsetup_standalone.exe --verbose --remote-package-repository=https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ --local-package-repository=C:\miktex --package-set=complete download && ./miktexsetup_standalone.exe --verbose --local-package-repository=C:\miktex --package-set=complete install && cd ..

      - name: Build SRGAN-Korean
        shell: pwsh
        run: "& \"C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.exe\" -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-directory=korean -aux-directory=auxil SRGANpaper_CVPR_Arxiv.tex"

      - name: Fix tex file for SRGAN-EngKor
        run: (Get-Content -Path SRGANpaper_CVPR_Arxiv.tex -Raw) -Replace "\\newcommand\{\\eng\}\[1\]\{\}", "\newcommand{\eng}[1]{`n`n#1`n`n}" > SRGANpaper_CVPR_Arxiv-EngKor.tex && mv SRGANpaper_CVPR_Arxiv-EngKor.tex SRGANpaper_CVPR_Arxiv.tex -Force

      - name: Build SRGAN-EngKor
        shell: pwsh
        run: "& \"C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.exe\" -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -output-directory=engkor -aux-directory=auxil SRGANpaper_CVPR_Arxiv.tex"

      - name: Rename
        shell: pwsh
        run: mv korean\SRGANpaper_CVPR_Arxiv.pdf SRGAN-Korean.pdf && mv engkor\SRGANpaper_CVPR_Arxiv.pdf SRGAN-EngKor.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: papers
          path: |
            SRGAN-Korean.pdf
            SRGAN-EngKor.pdf
