name: Build papers
on: [push, pull_request]
jobs:
  launch_test:
    name: Build papers
    runs-on: ubuntu-22.04
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install prerequisite
        run: sudo apt-get update && sudo apt-get install texlive-full -y

      - name: Build SRGAN-Korean
        run: pdflatex -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -jobname=SRGANpaper_CVPR_Arxiv -aux-directory=./auxil/ SRGANpaper_CVPR_Arxiv.tex && mv SRGANpaper_CVPR_Arxiv.pdf SRGAN-Korean.pdf

      - name: Build SRGAN-EngKor
        run: sed -i 's/\\newcommand{\\eng}\[1\]{}/\\newcommand{\\eng}\[1\]{#1}/g' SRGANpaper_CVPR_Arxiv.tex && pdflatex -jobname=SRGAN-EngKor -aux-directory=./auxil/ SRGANpaper_CVPR_Arxiv.tex && pdflatex -jobname=SRGAN-EngKor -aux-directory=./auxil/ SRGANpaper_CVPR_Arxiv.tex && mv SRGANpaper_CVPR_Arxiv.pdf SRGAN-EngKor.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: papers
          path: |
            SRGAN-EngKor.pdf
            SRGAN-Korean.pdf