name: Build papers
on: [push, pull_request]
jobs:
  launch_test:
    name: Build papers
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: miktex-cache
        with:
          path: C:\Program Files\MiKTeX
          key: ${{ runner.os }}-230222
      - if: steps.miktex-cache.outputs.cache-hit != 'true'
        name: Install MiKTeX
        run: Invoke-WebRequest -Uri "https://miktex.org/download/win/miktexsetup-x64.zip" -OutFile "miktexsetup-x64.zip" && Expand-Archive miktexsetup-x64.zip && cd miktexsetup-x64 && ./miktexsetup_standalone.exe --verbose --remote-package-repository=https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ --local-package-repository="C:\Program Files\MiKTeX\lpr" --package-set=complete download && ./miktexsetup_standalone.exe --verbose --local-package-repository="C:\Program Files\MiKTeX\lpr" --package-set=complete install && cd ..

      - name: Build PDFs
        shell: pwsh
        run: ".\\build.ps1 \"C:\\Program Files\\MiKTeX\\miktex\\bin\\x64\\pdflatex.exe\""

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: papers
          path: |
            out/SRGAN-Korean.pdf
            out/SRGAN-Korean-Summary.pdf
            out/SRGAN-EngKor.pdf
            out/SRGAN-EngKor-Summary.pdf
