name: Build papers
on: [push, pull_request]
jobs:
  launch_test:
    name: Build papers
    runs-on: windows-2022
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Install prerequisite
        shell: pwsh
        run: Invoke-WebRequest -Uri "https://miktex.org/download/win/miktexsetup-x64.zip" -OutFile "miktexsetup-x64.zip" && Expand-Archive miktexsetup-x64.zip && cd miktexsetup-x64 && ./miktexsetup_standalone.exe --verbose --remote-package-repository=https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/ --local-package-repository=C:\miktex --package-set=complete download && ./miktexsetup_standalone.exe --verbose --local-package-repository=C:\miktex --package-set=complete install && cd ..

      - name: Build SRGAN-Korean
        shell: pwsh
        run: & C:\''Program Files''\MiKTeX\miktex\bin\x64\pdflatex.exe -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -jobname=SRGANpaper_CVPR_Arxiv -aux-directory=.\auxil\ SRGANpaper_CVPR_Arxiv.tex

#      - name: Build SRGAN-EngKor
#        run: sed -i 's/\\newcommand{\\eng}\[1\]{}/\\newcommand{\\eng}\[1\]{#1}/g' SRGANpaper_CVPR_Arxiv.tex && miktex/bin/x64/ -file-line-error -interaction=nonstopmode -synctex=1 -output-format=pdf -jobname=SRGANpaper_CVPR_Arxiv -aux-directory=./auxil/ SRGANpaper_CVPR_Arxiv.tex

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: papers
          path: |
            SRGAN-EngKor.pdf
            SRGAN-Korean.pdf